//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TaskProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TransferHistory
    {
        public int TransferID { get; set; }
        public Nullable<int> FromUserID { get; set; }
        public Nullable<int> ToUserID { get; set; }
        public decimal Amount { get; set; }
        public System.DateTime TransferDate { get; set; }
        public string Description { get; set; }
        public int FromAccountID { get; set; }
        public int ToAccountID { get; set; }
        public decimal RemainingBalance { get; set; }
        public decimal RecipientRemainingBalance { get; set; }
        public bool IsCanceled { get; set; }
    
        public virtual Accounts Accounts { get; set; }
        public virtual Accounts Accounts1 { get; set; }
        public virtual Users Users { get; set; }
    }
}
